apiVersion: batch/v1
kind: Job
metadata:
  name: dev-job
  namespace: team-a # Job under team-a namespace
  annotations:
    kueue.x-k8s.io/queue-name: lq-team-a # Point to the LocalQueue
    kueue.x-k8s.io/priority-class: dev-priority
spec:
  ttlSecondsAfterFinished: 60 # Job will be deleted after 60 seconds
  parallelism: 9 # This Job will have 3 replicas running at the same time
  completions: 9 # This Job requires 3 completions
  suspend: true # Set to true to allow Kueue to control the Job when it starts
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:latest
        args: ["120s"] # Sleep for 120 seconds
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
      restartPolicy: Never